language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"
install:
  - npm ci
script:
  - npm run lint
  - npm run test
  - npm run test-dist
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
